[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "valuation"
version = "0.0.1"
authors = [
  { name="David Thibodeau", email="dpthibodeau@umass.edu" },
  { name="George Bissias", email="gbiss@cs.umass.edu" },
]
description = "Item / bundle valuation"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
                "numpy >= 1.26.1",
                "scipy >= 1.11.3",
               ]